version: '3.5'

volumes:
  redis-data:
services:
  redis:
    image: redis:6.2-alpine
    container_name: ${REDIS_CONTAINER_NAME:-redis}
    restart: always
    volumes:
      - ${REDIS_VOLUME:-redis-data}:/var/lib/redis
      # - ./redis-data/redis-server.log:/var/log/redis/redis-server.log
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: > 
      redis-server 
      --requirepass ${REDIS_ROOT_PASSWORD:-root}
      --bind 0.0.0.0
      --save ""
      --appendonly no
      --dir /var/lib/redis
      --maxmemory 2048M
      --maxmemory-policy volatile-ttl
    links: 
      - redis-commander
    healthcheck:
      test: redis-cli -a "${REDIS_ROOT_PASSWORD:-root}" ping
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${REDIS_COMMANDER_CONTAINER_NAME:-redis-commander}
    restart: always
    environment:
      - REDIS_HOST=${REDIS_CONTAINER_NAME:-redis}
      - REDIS_PASSWORD=${REDIS_ROOT_PASSWORD:-root}
      - HTTP_USER=${HTTP_USER:-admin}
      - HTTP_PASSWORD=${HTTP_PASSWORD:-123456a@}
    ports:
      - ${REDIS_COMMANDER_PORT:-8084}:8081
