# Service Config
SERVICE_HOST = "0.0.0.0"
SERVICE_PORT = 9030
TOKEN_EXPIRES = 14400 # 4 hours
SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"

# Database Config
MARIADB_HOST = "172.21.100.167"
MARIADB_PORT = 3306
MARIADB_DB_NAME = "xface_system"
MARIADB_USERNAME = "root"
MARIADB_PASSWORD = "root"

# Kafka Config
KAFKA_SERVER_HOST = "172.21.100.167"
KAFKA_SERVER_PORT = 9092
KAFKA_CONSUMER_GROUP_ID = "detect2db"
